# Generated by Django 4.2.4 on 2023-08-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_person_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="person",
            name="middle_name",
            field=models.CharField(max_length=20),
        ),
    ]
